sudo: required



language: generic


services:
  - docker


before_install:
  - echo "[build] make docker image"
  - docker build -t jjjhhhvvv/docker-with-app:1.0.0 -f Dockerfile.dev ./

script:
  - docker run -e CI=true jjjhhhvvv/docker-with-app:1.0.0 npm run test -- --coverage

after_script:
  -  echo "TEST SUCCESS!"